In [6]:
using LinearAlgebra

M = [0 0.5 0 1/3 ; 1 0 0 1/3 ; 0 0.5 0 1/3 ; 0 0 1 0]

M1 = [0 .425 0 .283 ; .85 0 0 .283 ; 0 .425 0 .283 ; 0 0 .85 0]

a = [.0375 .0375 .0375 .0375 ; .0375 .0375 .0375 .0375 ; .0375 .0375 .0375 .0375 ; .0375 .0375 .0375 .0375]

M2 = M1 + a

M3 = .85 * M + a
valM,vecM = eigen(M3)

println(M3)

b = vecM[:,4]

#sum = sum(b)

prob_vector = b ./ sum(b)

[0.0375 0.46249999999999997 0.0375 0.3208333333333333; 0.8875 0.0375 0.0375 0.3208333333333333; 0.0375 0.46249999999999997 0.0375 0.3208333333333333; 0.0375 0.0375 0.8875 0.0375]


4-element Vector{Float64}:
 0.23202579826601816
 0.30122647494184823
 0.23202579826601816
 0.23472192852611545

In [25]:
function naive_pagerank(M)
    # REQUIRES M is Markov matrix
    rows = size(M, 1)
    
    valM, vecM = eigen(M)

    b = vecM[:, rows]
    # last eigenvector is always 1 (given M is markov matrix)

    prob_vector = b ./ sum(b)
    return prob_vector
end 

naive_pagerank (generic function with 1 method)

In [30]:
function pagerank(M)
    # REQUIRES M is Markov matrix
    # if M is regular, no need to adjust !!
    # make A be the matrix adding random where A has same dimensions of M with entries .15/len(M)
    rows = size(M, 1)
    cols = size(M, 2)
    A = zeros(rows, cols)

    for i = 1:rows
        for j = 1:cols
            A[i, j] = 0.15 / rows
        end 
    end
    

    M1 = 0.85 * M + A
    valM, vecM = eigen(M1)
    b = vecM[:, rows]
    # lam = valM[rows]
    # println(round(lam) == 1)
    
    # last eigenvector is always 1 (given M is markov matrix)
    prob_vector = b ./ sum(b)
    return prob_vector
end 

pagerank (generic function with 1 method)

In [ ]:
pagerank(M)

true


4-element Vector{Float64}:
 0.23202579826601816
 0.30122647494184823
 0.23202579826601816
 0.23472192852611545

In [26]:
using LinearAlgebra

M = [0 0.5 0 1/3 ; 1 0 0 1/3 ; 0 0.5 0 1/3 ; 0 0 1 0]

naive_pagerank(M)

4-element Vector{Float64}:
 0.23076923076923075
 0.30769230769230754
 0.23076923076923087
 0.2307692307692309

In [28]:
using LinearAlgebra

M = [0 0 1 0 0 ; 0 0 0 0 0 ; 1 1 0 0 0 ; 0 0 0 0 1 ; 0 0 0 1 0]

naive_pagerank(M)

5-element Vector{Float64}:
 -0.0
 -0.0
 -0.0
  0.5
  0.5

In [31]:
using LinearAlgebra

M = [0 0.5 0 1/3 ; 1 0 0 1/3 ; 0 0.5 0 1/3 ; 0 0 1 0]

pagerank(M)

4-element Vector{Float64}:
 0.23202579826601816
 0.30122647494184823
 0.23202579826601816
 0.23472192852611545

In [32]:
using LinearAlgebra

M = [0 0 1 0 0 ; 0 0 0 0 0 ; 1 1 0 0 0 ; 0 0 0 0 1 ; 0 0 0 1 0]

pagerank(M)

5-element Vector{Float64}:
 0.27810810810810827
 0.02999999999999999
 0.291891891891892
 0.1999999999999999
 0.1999999999999999

In [ ]:
website1 = [0 ; 1 ; 0 ; 0]
website2 = [0.5 ; 0 ; 0.5 ; 0]
website3 = [0 ; 0 ; 0 ; 1]
website4 = [1/3 ; 1/3 ; 1/3 ; 0]

for j = 1:length(website1)
    websites[]
websites = 


16-element Vector{Float64}:
 0.0
 1.0
 0.0
 0.0
 0.5
 0.0
 0.5
 0.0
 0.0
 0.0
 0.0
 1.0
 0.3333333333333333
 0.3333333333333333
 0.3333333333333333
 0.0